/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface Sb3SideDrawer {
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface Sb3SideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'Sb3SideDrawer': Components.Sb3SideDrawer;
  }

  interface StencilIntrinsicElements {
    'sb3-side-drawer': Components.Sb3SideDrawerAttributes;
  }


  interface HTMLSb3SideDrawerElement extends Components.Sb3SideDrawer, HTMLStencilElement {}
  var HTMLSb3SideDrawerElement: {
    prototype: HTMLSb3SideDrawerElement;
    new (): HTMLSb3SideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'sb3-side-drawer': HTMLSb3SideDrawerElement
  }

  interface ElementTagNameMap {
    'sb3-side-drawer': HTMLSb3SideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
