/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface Sb3SideDrawer {
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface Sb3SideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }

  interface Sb3Tooltip {
    'tooltipContent': string;
  }
  interface Sb3TooltipAttributes extends StencilHTMLAttributes {
    'tooltipContent'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'Sb3SideDrawer': Components.Sb3SideDrawer;
    'Sb3Tooltip': Components.Sb3Tooltip;
  }

  interface StencilIntrinsicElements {
    'sb3-side-drawer': Components.Sb3SideDrawerAttributes;
    'sb3-tooltip': Components.Sb3TooltipAttributes;
  }


  interface HTMLSb3SideDrawerElement extends Components.Sb3SideDrawer, HTMLStencilElement {}
  var HTMLSb3SideDrawerElement: {
    prototype: HTMLSb3SideDrawerElement;
    new (): HTMLSb3SideDrawerElement;
  };

  interface HTMLSb3TooltipElement extends Components.Sb3Tooltip, HTMLStencilElement {}
  var HTMLSb3TooltipElement: {
    prototype: HTMLSb3TooltipElement;
    new (): HTMLSb3TooltipElement;
  };

  interface HTMLElementTagNameMap {
    'sb3-side-drawer': HTMLSb3SideDrawerElement
    'sb3-tooltip': HTMLSb3TooltipElement
  }

  interface ElementTagNameMap {
    'sb3-side-drawer': HTMLSb3SideDrawerElement;
    'sb3-tooltip': HTMLSb3TooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
